dataset:
  image_dir: ""
  image_edits_dir: ""
  eval_dir: /proj/vondrick4/VisualMacros/Photoshop/whiskers/train-b-90deg

diffusion:
  embedding_config:
    placeholder_strings: ["*"]
    initializer_words: ["red", "whiskers"]
    per_image_tokens: false
    num_vectors_per_token: 10
    progressive_words: false
  conditioning_dropout_prob: 0.05

ckpt_path: /proj/vondrick2/orr/projects/textual_inversion/magnification/results/bptt/90_deg/bsz_32_steps_50_gckpt_l1_lr1e-3/4/embedding_4.pt
output_dir: ./results/eval/90_deg/bsz_32_steps_50_gckpt_lr1e-3/cats_90deg
run_name: "4"
batch_size: 6
num_inference_steps: 100
device: 2