dataset:
  image_dir: /proj/vondrick4/VisualMacros/Photoshop/whiskers/train-a
  image_edits_dir: /proj/vondrick4/VisualMacros/Photoshop/whiskers/train-b
  eval_dir: /proj/vondrick4/VisualMacros/Photoshop/whiskers/eval-a
  repeats: 100

diffusion:
  embedding_config:
    placeholder_strings: ["*"]
    initializer_words: ["red", "whiskers"]
    per_image_tokens: false
    num_vectors_per_token: 10
    progressive_words: false
  conditioning_dropout_prob: 0.05

train:
  total_batch_size: 32
  total_samples_per_epoch: 256
  num_gpus: 4

  learning_rate: 3e-4

  use_lora: false
  grad_checkpoint: true
  truncated_backprop: true
  truncated_backprop_rand: true
  truncated_backprop_minmax: [50, 100]

log_dir: ./results/bptt/whiskers/full_unet_bsz_32_steps_100_gckpt_lr3e-4_trunc_rand_50_100
# log_dir: ./results/bptt/whiskers/check
run_name: check
num_checkpoint_limit: 10
mixed_precision: "no"
num_inference_steps: 100
epochs: 6
device: 3
allow_tf32: true
debug: true